name: MCMEPVP
main: co.mcme.pvp.MCMEPVP
version: 1.0.3
commands:
   pvp:
      description: PVP
      usage: /<command> [join|start|map|gt|set|stop]
   shout:
      description: Shout a message to Everyone!
      usage: /<command> [msg]
   a:
      description: Chat only for Admins!
      usage: /<command> [msg]